export const fake_data = [
  {
    id: "BAS1204",
    group: "05",
    name: "Giải tích 2",
    stc: "3",
    result_end: "8.0",
    score_10: "9.8",
    score_4: "3",
    score_c: "B",
  },
  {
    id: "INT1336",
    group: "07",
    name: "Mạng máy tính",
    stc: "3",
    result_end: "7.0",
    score_10: "8.8",
    score_4: "3.2",
    score_c: "A+",
  },
  {
    id: "ELE 1433",
    group: "07",
    name: "Kỹ thuật số",
    stc: "3",
    result_end: "8.0",
    score_10: "7.8",
    score_4: "3",
    score_c: "B+",
  },
  {
    id: "INT1336",
    group: "07",
    name: "Mạng máy tính",
    stc: "3",
    result_end: "7.0",
    score_10: "7.8",
    score_4: "3",
    score_c: "B",
  },
  {
    id: "ELE1319",
    group: "07",
    name: "Lý thuyết thông tin",
    stc: "3",
    result_end: "9.0",
    score_10: "9.8",
    score_4: "3",
    score_c: "A+",
  },
];
